"""add_assigned_at_to_orders

Revision ID: f77ccb29aa5f
Revises: 86621c51e171
Create Date: 2026-01-21 14:49:38.994311+00:00
"""

from typing import Sequence, Union

import sqlalchemy as sa
import geoalchemy2
from alembic import op


# revision identifiers, used by Alembic.
revision: str = 'f77ccb29aa5f'
down_revision: Union[str, None] = '86621c51e171'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('assigned_at', sa.DateTime(), nullable=True, comment='Время назначения водителя на заказ'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'assigned_at')
    # ### end Alembic commands ###
