"""add notification preferences

Revision ID: 9c4d8a7e2b1f
Revises: bead1875fb36
Create Date: 2026-01-26 16:00:00.000000+00:00
"""

from typing import Sequence, Union

import sqlalchemy as sa
import geoalchemy2
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9c4d8a7e2b1f'
down_revision: Union[str, None] = 'bead1875fb36'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'notification_preferences',
        sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column('driver_id', sa.BigInteger(), nullable=False, comment='ID водителя (пользователя)'),
        sa.Column('notification_type', sa.Enum('new_order', 'status_change', 'system_alert', 'driver_assignment', 'order_completion', name='notification_type', values_callable=lambda x: [e.value for e in x]), nullable=False, comment='Тип уведомления'),
        sa.Column('channel', sa.Enum('telegram', 'email', 'in_app', 'push', name='notification_channel', values_callable=lambda x: [e.value for e in x]), nullable=False, comment='Канал доставки уведомления'),
        sa.Column('frequency', sa.Enum('instant', 'hourly', 'daily', 'disabled', name='notification_frequency', values_callable=lambda x: [e.value for e in x]), nullable=False, comment='Частота отправки уведомлений'),
        sa.Column('is_enabled', sa.Boolean(), nullable=False, server_default=sa.text('true'), comment='Включена ли настройка'),
        sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False, server_default=sa.text('CURRENT_TIMESTAMP')),
        sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False, server_default=sa.text('CURRENT_TIMESTAMP')),
        sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
        comment='Настройки уведомлений пользователя'
    )
    op.create_index(
        op.f('ix_notification_prefs_driver_type_channel'),
        'notification_preferences',
        ['driver_id', 'notification_type', 'channel'],
        unique=True
    )
    op.create_index(
        op.f('ix_notification_preferences_driver_id'),
        'notification_preferences',
        ['driver_id'],
        unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_notification_preferences_driver_id'), table_name='notification_preferences')
    op.drop_index(op.f('ix_notification_prefs_driver_type_channel'), table_name='notification_preferences')
    op.drop_table('notification_preferences')
    # ### end Alembic commands ###
