"""add_order_details_fields

Revision ID: ada6f256ebbf
Revises: 7cd55e5e7f3e
Create Date: 2026-01-01 02:47:44.734725+00:00
"""

from typing import Sequence, Union

import sqlalchemy as sa
import geoalchemy2
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ada6f256ebbf'
down_revision: Union[str, None] = '7cd55e5e7f3e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('driver_location_history', sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='Время записи в БД'))
    op.alter_column('driver_location_history', 'id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('driver_location_history', 'driver_id',
               existing_type=sa.INTEGER(),
               comment='ID водителя',
               existing_nullable=False)
    op.alter_column('driver_location_history', 'location',
               existing_type=geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, dimension=2, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry', nullable=False, _spatial_index_reflected=True),
               comment='Координаты (WGS84)',
               existing_nullable=False)
    op.alter_column('driver_location_history', 'recorded_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               type_=sa.DateTime(),
               comment='Время фиксации координат водителем',
               existing_nullable=False)
    op.create_index('idx_driver_location_history_location', 'driver_location_history', ['location'], unique=False, postgresql_using='gist')
    op.create_index(op.f('ix_driver_location_history_driver_id'), 'driver_location_history', ['driver_id'], unique=False)
    op.create_index(op.f('ix_driver_location_history_recorded_at'), 'driver_location_history', ['recorded_at'], unique=False)
    op.alter_column('drivers', 'telegram_id',
               existing_type=sa.BIGINT(),
               comment='Telegram user ID',
               existing_nullable=False)
    op.alter_column('drivers', 'name',
               existing_type=sa.VARCHAR(length=255),
               comment='Имя водителя',
               existing_nullable=False)
    op.alter_column('drivers', 'phone',
               existing_type=sa.VARCHAR(length=20),
               comment='Номер телефона',
               existing_nullable=True)
    op.alter_column('drivers', 'status',
               existing_type=postgresql.ENUM('available', 'busy', 'offline', name='driver_status'),
               comment='Текущий статус',
               existing_nullable=False,
               existing_server_default=sa.text("'offline'::driver_status"))
    op.alter_column('drivers', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               comment='Флаг активности (разрешен ли вход в бот)',
               existing_server_default=sa.text('true'))
    op.drop_constraint(op.f('drivers_telegram_id_key'), 'drivers', type_='unique')
    op.drop_index(op.f('ix_drivers_telegram_id'), table_name='drivers')
    op.create_index(op.f('ix_drivers_telegram_id'), 'drivers', ['telegram_id'], unique=True)
    op.alter_column('orders', 'driver_id',
               existing_type=sa.INTEGER(),
               comment='FK на водителя',
               existing_nullable=True)
    op.alter_column('orders', 'status',
               existing_type=postgresql.ENUM('pending', 'assigned', 'driver_arrived', 'in_progress', 'completed', 'cancelled', name='order_status'),
               comment='Статус заказа',
               existing_nullable=False,
               existing_server_default=sa.text("'pending'::order_status"))
    op.alter_column('orders', 'priority',
               existing_type=postgresql.ENUM('low', 'normal', 'high', 'urgent', name='order_priority'),
               comment='Приоритет заказа',
               existing_nullable=False,
               existing_server_default=sa.text("'normal'::order_priority"))
    op.alter_column('orders', 'time_range',
               existing_type=postgresql.TSTZRANGE(),
               comment='Временной интервал выполнения (с таймзоной)',
               existing_nullable=True)
    op.alter_column('orders', 'pickup_location',
               existing_type=geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, dimension=2, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry', _spatial_index_reflected=True),
               comment='Координаты точки погрузки (WGS84)',
               existing_nullable=True)
    op.alter_column('orders', 'dropoff_location',
               existing_type=geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, dimension=2, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry', _spatial_index_reflected=True),
               comment='Координаты точки выгрузки (WGS84)',
               existing_nullable=True)
    op.alter_column('orders', 'comment',
               existing_type=sa.TEXT(),
               comment='Комментарий к заказу',
               existing_nullable=True)
    op.alter_column('orders', 'cancellation_reason',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.Text(),
               existing_nullable=True)
    op.drop_index(op.f('ix_orders_time_range_gist'), table_name='orders', postgresql_using='gist')
    op.create_index('idx_orders_dropoff_location', 'orders', ['dropoff_location'], unique=False, postgresql_using='gist')
    op.create_index('idx_orders_pickup_location', 'orders', ['pickup_location'], unique=False, postgresql_using='gist')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_orders_pickup_location', table_name='orders', postgresql_using='gist')
    op.drop_index('idx_orders_dropoff_location', table_name='orders', postgresql_using='gist')
    op.create_index(op.f('ix_orders_time_range_gist'), 'orders', ['time_range'], unique=False, postgresql_using='gist')
    op.alter_column('orders', 'cancellation_reason',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=500),
               existing_nullable=True)
    op.alter_column('orders', 'comment',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Комментарий к заказу',
               existing_nullable=True)
    op.alter_column('orders', 'dropoff_location',
               existing_type=geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, dimension=2, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry', _spatial_index_reflected=True),
               comment=None,
               existing_comment='Координаты точки выгрузки (WGS84)',
               existing_nullable=True)
    op.alter_column('orders', 'pickup_location',
               existing_type=geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, dimension=2, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry', _spatial_index_reflected=True),
               comment=None,
               existing_comment='Координаты точки погрузки (WGS84)',
               existing_nullable=True)
    op.alter_column('orders', 'time_range',
               existing_type=postgresql.TSTZRANGE(),
               comment=None,
               existing_comment='Временной интервал выполнения (с таймзоной)',
               existing_nullable=True)
    op.alter_column('orders', 'priority',
               existing_type=postgresql.ENUM('low', 'normal', 'high', 'urgent', name='order_priority'),
               comment=None,
               existing_comment='Приоритет заказа',
               existing_nullable=False,
               existing_server_default=sa.text("'normal'::order_priority"))
    op.alter_column('orders', 'status',
               existing_type=postgresql.ENUM('pending', 'assigned', 'driver_arrived', 'in_progress', 'completed', 'cancelled', name='order_status'),
               comment=None,
               existing_comment='Статус заказа',
               existing_nullable=False,
               existing_server_default=sa.text("'pending'::order_status"))
    op.alter_column('orders', 'driver_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='FK на водителя',
               existing_nullable=True)
    op.drop_index(op.f('ix_drivers_telegram_id'), table_name='drivers')
    op.create_index(op.f('ix_drivers_telegram_id'), 'drivers', ['telegram_id'], unique=False)
    op.create_unique_constraint(op.f('drivers_telegram_id_key'), 'drivers', ['telegram_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('drivers', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               comment=None,
               existing_comment='Флаг активности (разрешен ли вход в бот)',
               existing_server_default=sa.text('true'))
    op.alter_column('drivers', 'status',
               existing_type=postgresql.ENUM('available', 'busy', 'offline', name='driver_status'),
               comment=None,
               existing_comment='Текущий статус',
               existing_nullable=False,
               existing_server_default=sa.text("'offline'::driver_status"))
    op.alter_column('drivers', 'phone',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='Номер телефона',
               existing_nullable=True)
    op.alter_column('drivers', 'name',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='Имя водителя',
               existing_nullable=False)
    op.alter_column('drivers', 'telegram_id',
               existing_type=sa.BIGINT(),
               comment=None,
               existing_comment='Telegram user ID',
               existing_nullable=False)
    op.drop_index(op.f('ix_driver_location_history_recorded_at'), table_name='driver_location_history')
    op.drop_index(op.f('ix_driver_location_history_driver_id'), table_name='driver_location_history')
    op.drop_index('idx_driver_location_history_location', table_name='driver_location_history', postgresql_using='gist')
    op.alter_column('driver_location_history', 'recorded_at',
               existing_type=sa.DateTime(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               type_=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Время фиксации координат водителем',
               existing_nullable=False)
    op.alter_column('driver_location_history', 'location',
               existing_type=geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, dimension=2, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry', nullable=False, _spatial_index_reflected=True),
               comment=None,
               existing_comment='Координаты (WGS84)',
               existing_nullable=False)
    op.alter_column('driver_location_history', 'driver_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='ID водителя',
               existing_nullable=False)
    op.alter_column('driver_location_history', 'id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True)
    op.drop_column('driver_location_history', 'created_at')
    # ### end Alembic commands ###
