"""add customer notification fields

Revision ID: bead1875fb36
Revises: f77ccb29aa5f
Create Date: 2026-01-21 15:13:51.083168+00:00
"""

from typing import Sequence, Union

import sqlalchemy as sa
import geoalchemy2
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bead1875fb36'
down_revision: Union[str, None] = 'f77ccb29aa5f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('customer_telegram_id', sa.BigInteger(), nullable=True, comment='Telegram ID заказчика для уведомлений'))
    op.add_column('orders', sa.Column('customer_webhook_url', sa.String(length=500), nullable=True, comment='URL вебхука заказчика для уведомлений'))
    op.create_index(op.f('ix_orders_customer_telegram_id'), 'orders', ['customer_telegram_id'], unique=False)
    op.drop_column('orders', 'assigned_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('assigned_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True, comment='Время назначения водителя на заказ'))
    op.drop_index(op.f('ix_orders_customer_telegram_id'), table_name='orders')
    op.drop_column('orders', 'customer_webhook_url')
    op.drop_column('orders', 'customer_telegram_id')
    # ### end Alembic commands ###
