"""add onboarding fields to drivers

Revision ID: 46ecd9dfaa2c
Revises: bead1875fb36
Create Date: 2026-01-26 17:06:49.880929+00:00
"""

from typing import Sequence, Union

import sqlalchemy as sa
import geoalchemy2
from alembic import op


# revision identifiers, used by Alembic.
revision: str = '46ecd9dfaa2c'
down_revision: Union[str, None] = 'add_route_models_01'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('drivers', sa.Column('onboarding_completed', sa.Boolean(), nullable=False, server_default=sa.text('false'), comment='Завершён ли онбординг водителя'))
    op.add_column('drivers', sa.Column('onboarding_step', sa.String(length=50), nullable=True, comment='Текущий шаг онбординга'))
    op.add_column('drivers', sa.Column('onboarding_skipped', sa.Boolean(), nullable=False, server_default=sa.text('false'), comment='Был ли онбординг пропущен'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('drivers', 'onboarding_skipped')
    op.drop_column('drivers', 'onboarding_step')
    op.drop_column('drivers', 'onboarding_completed')
    # ### end Alembic commands ###
