/**
 * Мок-данные для dev-режима без подключения к бэкенду.
 */
import type { OrderResponse, DriverLocation, DriverResponse } from '../types/api';
import { OrderStatus, OrderPriority, DriverStatus } from '../types/api';

export const MOCK_DRIVERS: DriverResponse[] = [
    {
        id: 1,
        telegram_id: 123456,
        name: 'Иван Иванов',
        phone: '+7 900 123-45-67',
        status: DriverStatus.AVAILABLE,
        is_active: true,
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
    },
    {
        id: 2,
        telegram_id: 234567,
        name: 'Петр Петров',
        phone: '+7 900 234-56-78',
        status: DriverStatus.BUSY,
        is_active: true,
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
    },
    {
        id: 3,
        telegram_id: 345678,
        name: 'Сидор Сидоров',
        phone: '+7 900 345-67-89',
        status: DriverStatus.AVAILABLE,
        is_active: true,
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
    },
];

export const MOCK_DRIVER_LOCATIONS: DriverLocation[] = [
    {
        driver_id: 1,
        latitude: 55.7558,
        longitude: 37.6173,
        status: DriverStatus.AVAILABLE,
        updated_at: new Date().toISOString(),
    },
    {
        driver_id: 2,
        latitude: 55.7512,
        longitude: 37.6189,
        status: DriverStatus.BUSY,
        updated_at: new Date().toISOString(),
    },
    {
        driver_id: 3,
        latitude: 55.7601,
        longitude: 37.6254,
        status: DriverStatus.AVAILABLE,
        updated_at: new Date().toISOString(),
    },
];

const now = new Date();
const hourLater = new Date(now.getTime() + 60 * 60 * 1000);
const twoHoursLater = new Date(now.getTime() + 2 * 60 * 60 * 1000);

export const MOCK_ORDERS: OrderResponse[] = [
    {
        id: 1,
        driver_id: 1,
        status: OrderStatus.ASSIGNED,
        priority: OrderPriority.NORMAL,
        pickup_address: 'ул. Тверская, 1',
        dropoff_address: 'Красная площадь, 3',
        pickup_lat: 55.7558,
        pickup_lon: 37.6173,
        dropoff_lat: 55.7539,
        dropoff_lon: 37.6208,
        price: 450,
        time_start: now.toISOString(),
        time_end: hourLater.toISOString(),
        created_at: now.toISOString(),
        updated_at: now.toISOString(),
        comment: null,
        customer_name: 'Тестовый клиент 1',
        customer_phone: '+7 900 111-11-11',
        arrived_at: null,
        started_at: null,
        end_time: null,
        cancelled_at: null,
        cancellation_reason: null,
        route_geometry: null,
    },
    {
        id: 2,
        driver_id: 2,
        status: OrderStatus.IN_PROGRESS,
        priority: OrderPriority.HIGH,
        pickup_address: 'Арбат, 10',
        dropoff_address: 'Парк Горького',
        pickup_lat: 55.7512,
        pickup_lon: 37.5912,
        dropoff_lat: 55.7298,
        dropoff_lon: 37.6012,
        price: 650,
        time_start: now.toISOString(),
        time_end: twoHoursLater.toISOString(),
        created_at: now.toISOString(),
        updated_at: now.toISOString(),
        comment: 'Срочный заказ',
        customer_name: 'Тестовый клиент 2',
        customer_phone: '+7 900 222-22-22',
        arrived_at: null,
        started_at: now.toISOString(),
        end_time: null,
        cancelled_at: null,
        cancellation_reason: null,
        route_geometry: null,
    },
    {
        id: 3,
        driver_id: null,
        status: OrderStatus.PENDING,
        priority: OrderPriority.LOW,
        pickup_address: 'Ленинградский проспект, 15',
        dropoff_address: 'ВДНХ',
        pickup_lat: 55.7912,
        pickup_lon: 37.5534,
        dropoff_lat: 55.8267,
        dropoff_lon: 37.6389,
        price: 380,
        time_start: hourLater.toISOString(),
        time_end: twoHoursLater.toISOString(),
        created_at: now.toISOString(),
        updated_at: now.toISOString(),
        comment: null,
        customer_name: 'Тестовый клиент 3',
        customer_phone: '+7 900 333-33-33',
        arrived_at: null,
        started_at: null,
        end_time: null,
        cancelled_at: null,
        cancellation_reason: null,
        route_geometry: null,
    },
];
